name: duy
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - pip: 
    - voila
    - fastai
    - fastbook
    - ipywidgets
    - scikit-image
    - pillow